- aeg2225.md
> Added file with my UNI.

- ew2664.md
Created ew2664.md for HW0B and added some project and contributions ideas.
> HW0: Create ew2664.md

- gds2133.md
Added gds2133.md containing project and contribution ideas (all in Python)
> Add gds2133.md

- sip2109.md
Added project proposal in the form of sip2109.md.
> Add project proposal

- dme2136.md
> Added uni file

- cl3945.md
- tkp2108.md
HW0b with project proposals and contribution ideas
> updated cl3945.md

- mjk2244.md
Matt Kim mjk2244 HW 0 - project proposals and contributions
> mjk2244 HW0

- jcr2211.md
> added jcr2211 project proposal

- sst2147.md
HW0: Project Proposal (UNI: sst2147). Includes ideas for project proposal & project contributions.
> HW0: Project Proposal (UNI: sst2147)

- ss5945.md
Revised HW0 PR that keeps Prof. Paine's md file.
> HW0: ss5945 Revised PR

- oko2107.md
> added oko2107.md for HW0

- README.md
- tc3117.md
- UNI: tc3117
- Both proposal and contributions are still tentative.
> Update project proposal and project contributions

- uyo2000.md
also contains the link to the README for HW1
> HW0: add markdown file

- projects/python/numba.md
- projects/python/terminal-history.md
- students/ma4338.md
Rebased, resolved conflict and squashed commits
> HW2: Resolved Conflict

- projects/cpp/AudioMoth.md
- projects/cpp/hybriddatastructures.md
- students/al4007.md
> HW2 - squash and resolve conflicts 

- projects/javascript/color-template.md
- projects/javascript/material-ui.md
- students/cl3945.md
Added personal README to proposal file, created project files, and added the project repo link to the file
> HW2: Rebased onto main branch

- projects/python/MC_Toolbox.md
- projects/python/PyScript.md
- students/jm5025.md
update project repo link for MC_Toolbox.md
fix relative links in jm5025.md
> HW2 jm5025

- projects/python/matplotlib.md
- projects/python/palettes.md
- students/ys3593.md
Create proposal.md
Update proposal.md
Create contribution.md
Update contribution.md
Update ys3593.md
Update ys3593.md
add to projects folder
link added
> HW2: ys3593

- projects/python/pyvts.md
- projects/python/vtuberstudio.md
- students/kz2442.md
update kz2442.md vtubestudio.md, create pyvts.md
> HW2: kz2442 part 2 (new pull, please ignore my closed hw2 request)

- projects/python/interactive-score-editor.md
- projects/python/librosa.md
- students/sg3790.md
- Adding link to README,
- Separating out the proposals
- Adding the link to the project repository
- Fix links to project readme and contribution readme
> HW2 sg3790 (all commits squashed)

- projects/python/pro-football-reference-web-scraper.md
- projects/python/pydfs-lineup-optimizer.md
- students/mjk2244.md
Create pro-football-reference-web-scraper.md
wrote project description
linked project proposal
Create pydfs-lineup-optimizer.md
linked project contribution md file
creating python folder within projects w/temp. filler file
Revert "creating python folder within projects w/temp. filler file"
This reverts commit 84d44638c7d718acb97539f15e125f601cd8fbfd.
moving project proposal to python folder
moving project contribution doc to python folder
Update mjk2244.md with relative links
move mjk2244.md to students folder
added project repo badge to project file
> HW2 mjk2244

- projects/python/axiompy.md
- projects/python/objectify.md
- students/rjw2160.md
Squash:
- Add GitHub README to rjw2160.md (HW0)
- HW1: Add rjw2160 proposal/contribution
- HW2: Add repo link for rjw2160 project file
> HW2: Add repo link for rjw2160 project file

- mw3071.md
redid HW0 to separate HW0 and HW1
> HW0B create mw3071.md

- projects/python/mitiq.md
- projects/python/sec-web-scraper.md
- students/oko2107.md
I squashed the commits for HW 2! I have also created my project repo
> HW2 : [UNI:oko2107] squashed commits for hw2

- projects/javascript/snarkyjs.md
- projects/python/zkpy.md
- students/sm4967.md
HW1 P1: Added personal Github README
HW1 P3: Added project proposal md file
HW1 P3: Added project contributions md file
HW1 P3: Updated sm4967.md, project proposal and project contributions have links that point to md files
HW2 P2: Added link to project repo
> HW2 sm4967

- projects/python/fundy.md
- projects/python/scrapy.md
- students/smh2278.md
Update smh2278.md
added md files
Update smh2278.md
Update fundy.md
Update fundy.md
Update scrapy.md
Update scrapy.md
Update smh2278.md
> HW2: Add project link to smh2278.md, rebase with main

- projects/python/pybaseball.md
- projects/python/usau-scraper.md
- students/eem2188.md
- Added in project files for pybaseball and usau-scraper
- Edited eem2188.md to include project links
- Rebased and squashed all commits into one commit
Had to force push in order to rebase the commits that had already been pushed.
> HW2: Adding in Rebased HW1 Commits for eem2188

- projects/python/dash.md
- projects/python/youtubecommentmanager.md
- students/nhc2117.md
Create validator.py.md
Create dash.md
Update dash.md
Update nhc2117.md
Update nhc2117.md
Updated project info and added link to repo
> HW2: fix conflicts with rebase

- projects/javascript/custoplayer.md
- projects/javascript/jotai.md
- students/ea2905.md
✨ Added jotai.md proposal
🔗 Added links to proposals
📝 Added extra specificity on jotai proposal
🚒 Moved project into projects/javascript 📁
🔗 Changed proposal links from absolute to relative
🔗 Added repo link to custoplayer proposal
> HW2 (ea2905) Added custoplayer and jotai project proposals

- projects/javascript/calculator.md
- projects/python/notification.md
- students/ks3651.md
Rename To-do List to To-do List.md
Update To-do List.md
Create projects.md
Rename projects.md to project_ideas.md
Update project_ideas.md
Create plan.md
Update plan.md
Update ks3651.md
Update ks3651.md
change links of projects
Delete contribution directory
Update and rename To-do List.md to calculator.md
Update and rename project_ideas.md to notification.md
> HW2: Rebase

- projects/python/matplotlib.md
- projects/python/polling-bot.md
- students/grn2112.md
Create pollingbot.md
Create matplotlib.md
Update grn2112.md
Update and rename pollingbot.md to polling-bot.md
> HW2: Rebase HW1 changes

- projects/python/multi-scale-expansion.md
- projects/python/tensorflow.md
- students/aem2283.md
Resolved file conflicts, fixed file locations and redundancies
> HW 2 aem2283 - file conflicts resolved 

- projects/python/kms-encryption-tool.md
- projects/python/kubernetes.md
- projects/python/openverse-api.md
- projects/python/python-slack-sdk.md
- projects/python/zulip.md
- students/si2400.md
I have squashed all the commits into one. Thanks for suggesting the tips.
> HW2: relative path fix

- projects/python/matplotlib.md
- projects/python/spotify_to_apple.md
- students/baa2159.md
Update baa2159.md
Update readme link
Move to projects -> python
move to projects -> python
Update baa2159.md
remove unnecesary files
link and folder restructure
> HW2: Rebased and Fixed Conflicts

- projects/cpp/hybriddatastructures.md
Changing focus of personal project
> Update personal project description (change in project focus)

- projects/python/MC_Toolbox.md
- projects/python/mctk.md
- students/jm5025.md
rename MC_Toolbox as mctk
update project link
> Rename Project jm5025

- projects/cpp/SerenityOS.md
- projects/cpp/multithreading.md
- students/afs2185.md
add multithreading library description
Add serenity description
Add link to markdown files
fix path
add hw2 link
> HW2 - afs2185

- projects/python/pytest.md
- projects/python/sportsbox.md
- students/dh3116.md
added project proposal and contribution links
Create .gitkeep
Create .gitkeep
moved file to projects folder
moved file to folder
moved to proper folder
Rename projects/Project Idea.md to projects/python/Project Idea.md
Rename Project Idea.md to Project-Idea.md
used relative links
Rename Project Contribution Choice.md to Project-Contribution-Choice.md
narrowed to one choice
renamed to project name
renamed to contribution choice
Delete .gitkeep
Delete .gitkeep
had to refix links because i botched rebase hw
> HW2: project idea and contribution choice files

- projects/python/geopandas.md
- projects/python/soccer-api-wrapper.md
- students/dme2136.md
> HW2: handled conflicts

- projects/python/pydigree.md
- projects/python/pynrm.md
- students/hj2589.md
Add profile README link
Add pynrm.md
Add pydigree.md
Moved pynrm.md and pydigree.md under projects/python
Update links for pynrm.md and pydigree.md
Add link to project repository
> HW2 hj2589

- projects/python/betteR20.md
- projects/python/historical-timelines.md
- students/sip2109.md
Note: I also changed my project idea.
> HW2: sip2109

- projects/javascript/mingly.md
- projects/python/itzma-lint.md
- projects/python/lottie.md
- students/tc3117.md
author Tattie Chitrakorn <74645283+tchitrakorn@users.noreply.github.com> 1675569332 -0500 committer Tatt Chitrakorn <tatt.chitrakorn@gmail.com> 1676275148 -0500
HW1: Added GitHub README and updated proposal
Create itzma-lint.md
Update tc3117.md
Create lottie.md
Update tc3117.md
Update itzma-lint.md
Create mingly-issues.md
Update mingly-issues.md
Update tc3117.md
Create test.txt
Rename mingly-issues.md to projects/javascript/mingly-issues.md
Rename lottie.md to projects/python/lottie.md
Rename itzma-lint.md to projects/python/itzma-lint.md
Update tc3117.md
Update tc3117.md
Delete test.txt
Update tc3117.md
Update tc3117.md
Added project repo link and fixed relative paths
> HW2 - Correct PR

- projects/python/FinRL.md
- projects/python/crypto-trading.md
- students/zx2325.md
adding proposal for projects
commented changes
hw2 part1
> HW2: zx2325

- projects/python/TheAlgorithms-Python.md
- projects/python/print-structure.md
- students/dh3027.md
> HW2 (dh3027)

- students/kz2442.md
Add PyPI and my first contribution link to kz2442.md
> HW6: Add PyPI and contribution link to kz2442.md

- projects/python/Resume-Parser.md
- students/ss5945.md
Fixed linting for headers
Fixed linting and added PyPI link
Removed dupe headers
Added link to first contribution
> HW6 Part 5: Add first contribution in ss5945.md

- projects/python/Resume-Parser.md
- students/ss5945.md
Fixed linting for headers
Fixed linting and added PyPI link
Removed dupe headers
> HW6 Part 2: Add PyPI profile link to ss5945.md

- students/sa3883.md
Updated the name of the personal project and added contribution link
> HW6 part5: README.md updated with contribution

- projects/typescript/judgemental.md
- projects/typescript/tool-kit.md
- students/an3056.md
HW6 is already complete and merged. This PR is just to change the name of my proj. NPM said my old name was too close to someone else's packages and then the tags / versioning got all out of sorts so this is the same exact repo and project, but with a different name
> Chore: Change name of project

- students/amz2145.md
> HW 6 Part 2: Add PyPI

- students/sg3790.md
Homework 6; links to pypi profile and pull request for first contribution
> HW6: pypi and first contribution (sg3790)

- students/ac5003.md
Added PyPI link to ac5003.md
Added 1st contribution pr link to ac5003.md
> Hw6 Part 5: Added Contribution PR Link for kbmod to ac5003.md & Hw6 Part 2 Commit

- students/amz2145.md
Add link to open PR in Cilium for HW 6 Part 5
> HW 6 Part 5: Add link to Cilium PR

- students/aem2283.md
Created account and added link to pypi user account
> HW 6 Updating profile with pypi link

- students/el3030.md
Homework 6 part 5 for el3030: made a PR on an open source project and included the PR's link in my markdown file.
> Hw6 Part 5 el3030

- students/oko2107.md
Added my PyPI link to my readMe file
> [HW6] Updated oko2107.md with  PyPI link

- students/jed2192.md
Update jed2192.md: Links to PyPI account and first contribution
> HW 6: Part 2, 5

- students/ys3593.md
add the link to the pull request
> HW6_Part5: add the link to the pull request

- students/oko2107.md
> Added my contribution for HW6  to CP-algorithms

- students/imb2139.md
Add PyPI account link and first PR link.
> HW6: imb2139

- students/fk2421.md
fk2421 Contributed to Spring Boot Documentation as part of HW6 Part 5
> HW6 Part 5 fk2421: Added Contribution PR Link (first contribution)

- students/jp4013.md
PyPI Profile Link instead of Project Link
> HW6 Pt2 PR

- projects/python/sympy.md
- students/gds2133.md
HW6 Part 5: added open source contribution link to readme
> HW6 Part 5: add open source contribution

- projects/python/sympy.md
- students/gds2133.md
HW6 Part 2: add PyPI link to README
> HW6 Part 2: add PyPI link to gds2133.md

- projects/golang/buf.md
addressing feedback: https://github.com/ColumbiaOSS/project-proposals-s2023/pull/179 
unfortunately I had missed PR feedback on the old PR had not added my contributing project to this repo
> im2594: hw1 part3

- students/aj2604.md
First contribution was rejected.
Second contribution is open.
> Added link to two contributions

- projects/javascript/jobAppAutofiller.md
- projects/python/chatGPTCoverLetterGenerator.md
- students/jp4013.md
I’ve ended up finishing up rebasing and squashing the commits and opened a pull request from the OH today. It was super helpful. It’s quite delayed but I’m wondering if it qualifies to recover any points for the homework. It's still cool if not.
I think this is the single commit that shows the squashed commits
https://github.com/ColumbiaOSS/project-proposals-s2023/commit/51f96e94e50a1b42df71ca705338871f86789331
> HW2-jp4013 Post-Successful Rebase Redux

- projects/python/usau-scraper.md
- students/eem2188.md
Added in contribution link to my profile page, and added in badge links to my project page.
> HW8: Add in Contribution 2 Link to Profile and Updated Project Page

- students/ks3651.md
Made first contribution (implemented a function in Javascript)
> First Contribution

- projects/python/notification.md
- students/ks3651.md
- Made a second contribution and add a link to the personal markdown file
- Update the project’s markdown file as the instruction
> HW8: Second Contribution and Proposal Update

- students/im2594.md
Hi Professor,
Regarding my contribution PR, I noticed that the PR was not merged in due to a CLA sign issue, while I tried to resolved this issue I accidentally rebased that caused some unexpected issue on this original PR I had: https://github.com/bufbuild/buf/pull/2003
I have created a new PR to resolve this and how my CLA Signing is working and just waiting for a +1 from a project maintainer. Sorry for the inconvenience. Please kindly merge in this new updated PR link. Thank you so much.
> Resolving contribute PR issue

- projects/javascript/chatGPTCoverLetterGenerator.md
- projects/python/chatGPTCoverLetterGenerator.md
- students/jp4013.md
jp4013 - Final squash
jp4013 - Squashing commits
jp4013 - Lint error double blank lines
jp4013 - More lint fixes
> jp4013 - Markdowns Updated

- projects/python/age3d.md
- students/ac5003.md
- Added Badges from Project Repo to age3d.md
- Modified Description of project in age3d.md
- Added 2nd Contribution to Sympy to ac5003.md
> Updated age3d.md with Badges & Added 2nd Contrib to ac5003.md

- projects/python/insta-captions.md
- students/dc3448.md
- Moved insta-captions.md to the python folder as it is a python project
- Added  badges to insta-captions.md
- Updated students/dc3448.md to reflect
> Updated student and project information

- projects/python/FinRL.md
- projects/python/crypto-trading.md
- students/zx2325.md
> HW8: add contribution and update markdown files

- students/ua2182.md
Added PyTorch contribution info, both the issue link and my PR link added.
> [HW8] Add second project contribution

- projects/javascript/mongo-db-wrapper.md
- students/im2594.md
Hi professor @timkpaine I noticed that my prosopal .md file [PR](https://github.com/ColumbiaOSS/project-proposals-s2023/pull/179/files#diff-0538cedd35b25a1ae0a5a89f510452fb0567581289c8abdfcd8abe938be8a5fe) was not merged, I have re-created the proposal .md file in this PR. Thank you
> im2594: HW8

- projects/python/sec-web-scraper.md
- students/oko2107.md
- Added my contribution to my personal readMe
- Added relevant links to project readmE
> Added HW8 Contribution plus updated personal readme

- projects/python/stixx.md
- students/mg4145.md
I have updated both Markdown files.
> Hw8 - Updated Project and Students MD

- projects/python/pyvts.md
- students/kz2442.md
* Update project markdown `pyvts.md`
* Update personal markdown file `kz2442.md`
> HW8: kz2442

- projects/python/Augmentum.md
- projects/python/image_augmentation.md
- students/kk3084.md
Aside Note: Completed HW7 on May 6th (can I please get a regrade for this assignment).
> Added HW8 contribution, improved project description, and added badges

- projects/solidity/poseidon-sol.md
- students/yn2411.md
- add npm link
- add first contribution PR link
- add second contribution PR link
> HW6&HW8: Update profile 

- projects/python/clip_bbox.md
My HW8 was already merged but I later realized that my project's license badge had a broken link
> Fix broken license badge (HW8)

- projects/python/ez-parse.md
- students/ss5945.md
Fixed build status badge link in ez-parse.md and a minor typo in ss5945.md
> Final: Fixed build status badge link and a minor typo

- projects/python/QuickReaderPDF.md
- students/sb4696.md
HW8:sb4696 added new contributions
> HW8:sb4696 added new contributions

- projects/python/osd-slides.md
- students/kk3528.md
updated project with badges and slot for contribution
> updated project with badges and slot for contribution

- projects/python/spotify_to_apple.md
- students/baa2159.md
Updating my PR for HW8
Summary
--------
-Updated project page
- Updated student page to add my latest contribution to an open source project
> HW8 Updated PR
